### ISSUE TITLE
Error when using reverb

### ISSUE THREAD

**Issue by enbeec** [robobluebird/picotune#1]
I took a look at the code but couldn't quite grok how the reverb is supposed to work. Here's the input and output causing the error.

## tune

```
tune dmaj
sequence ph1

instrument i1
tone square
volume half
pan center
reverb some

phrase ph1
tempo 100
beats 8
subbeats 2
melodies
i1 p1

pattern p1 D3 . . . F#3 . . . G3 . . . D4 G3 F#3 D3
```

## output 

```
Traceback (most recent call last):
	13: from /usr/local/bin/picotune:23:in `<main>'
	12: from /usr/local/bin/picotune:23:in `load'
	11: from /var/lib/gems/2.7.0/gems/picotune-0.0.7/bin/picotune:4:in `<top (required)>'
	10: from /var/lib/gems/2.7.0/gems/picotune-0.0.7/lib/picotune.rb:33:in `wav'
	9: from /var/lib/gems/2.7.0/gems/picotune-0.0.7/lib/picotune.rb:198:in `wav'
	8: from /var/lib/gems/2.7.0/gems/picotune-0.0.7/lib/picotune.rb:179:in `buffer'
	7: from /var/lib/gems/2.7.0/gems/picotune-0.0.7/lib/picotune.rb:179:in `each'
	6: from /var/lib/gems/2.7.0/gems/picotune-0.0.7/lib/picotune.rb:182:in `block in buffer'
	5: from /var/lib/gems/2.7.0/gems/picotune-0.0.7/lib/picotune.rb:243:in `buffer'
	4: from /var/lib/gems/2.7.0/gems/picotune-0.0.7/lib/picotune.rb:243:in `each'
	3: from /var/lib/gems/2.7.0/gems/picotune-0.0.7/lib/picotune.rb:253:in `block in buffer'
	2: from /var/lib/gems/2.7.0/gems/picotune-0.0.7/lib/picotune.rb:253:in `each_with_index'
	1: from /var/lib/gems/2.7.0/gems/picotune-0.0.7/lib/picotune.rb:253:in `each'
/var/lib/gems/2.7.0/gems/picotune-0.0.7/lib/picotune.rb:293:in `block (2 levels) in buffer': undefined method `add' for nil:NilClass (NoMethodError)
```

**Comment by robobluebird** [comment]
Hello! Thanks for trying out the gem :) this error means that we expected to have a Sample to call “add” with but instead we have nil.

I am on mobile so my capability is limited but here’s the short version: we have a buffer named “temp” that holds our current melody only when reverb is on, because we have to apply the reverb to the melody before finally adding it to the overall phrase (which is kept in the variable “samples”) otherwise we would accidentally apply reverb to the entire phrase rather than just the one melody. Further, sometimes because of our need to “finish” a melody’s notes our buffer may extend beyond what we expect the buffer_size to be. I believe this is the case for the error.

there definitely needs to be a more rubust fix to this but for now you can replace line 293 with this:

`samples[i] = (samples[i] || PicoTune::Sample.new).add temp[i]`

which will at least ensure that there’s something to add to when adding the reverbed melody samples to the phrase samples.

Thanks again!

**Comment by robobluebird** [comment]
Got to the computer today, fixed the issue and pushed v 0.0.8 to rubygems.org as well as committing to the repo. Tested with your tune "dmaj" and all is well!

**Comment by enbeec** [comment]
Amazing! I haven't had a chance to sit down since I submitted the issue but I can't wait to try the reverb once I do!

**Comment by robobluebird** [comment]
No rush of course, I’m just happy to have you take interest! 🥳
